# Dockerfile for Quasar 2 with Vite using Yarn and apt-get
FROM node:18

# Install any dependencies needed with apt-get
# RUN apt-get update && apt-get install -y \
#     # Adicione pacotes necessários aqui, se houver
#     && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the frontend source code
COPY . .

# Install Yarn globally
RUN corepack enable && corepack prepare yarn@stable --activate

# Install project dependencies using Yarn
RUN yarn install

# Build the frontend
RUN yarn build

# Expose the frontend on port 8081
EXPOSE 9000

# Start the frontend server
CMD ["yarn", "dev"]
